### PR TITLE
Remove a bunch of summoning spells

### PR DESCRIPTION
**Pull request by alexjurkiewicz**
Summoning school is pretty amazing in hellcrawl. I think it's oppressively amazing, in that it's so good any character investing in magic wants a significant chunk of XP in summoning, which makes all mage characters more homogenous than would be ideal.

There are a few problems:
* Hellcrawl changes have made summons better
* Summoning was already great
* There are a lot of summoning spells compared to other spell schools
* Lots of summoning spells aren't that different from one another

Here's what I think the solution should be:
* Most summon spells should be dual-school
* Summoning spells should be pared down to reduce redundancy
* Playing as a summoning-focused player should have a particular rhythm through the game where depending on the spell levels you're up to and spell schools you've branched into, you will have various strengths and weaknesses.

So this PR makes the following changes:

Level 1:
* Removed: Summon butterflies
* Modified: Summon Small Mammal. Spell power cap is 200. Summons 1-10 mammals based on on spellpower. Powerlevel at spellpower under 20 is basically the same. Above that level, it will fill the "summon spam" niche sbutterflies used to hold. Not as effectively, of course.

Level 2:
* Unchanged: Call Imp

Level 3:
* Removed: Canine Familiar. Comparing imps & canines, canines get SInv and a bit more health, imps get better damage. Removing canines opens up space for guardian golem to become a more used spell.
* Unchanged: Recall
* Unchanged: Guardian Golem

Level 4:
* Unchanged: Summon Ice Beast
* Removed: Summon Lightning Spire. This spell is really fun to use and micromanaging double zaps is good gameplay, but I think it encourages degenerate gameplay of its own as a result of its immobility/placeability. I would be open to removing summon ice beast instead of this one.

Level 5:
* Removed: Summon Mana Viper. Three level 5 summons is at least one too many. Mana Vipers were the most oppressively good so I chose to cut them.
* Unchanged: Summon Demon
* Unchanged: Summon Forest

Level 6:
* Removed: Shadow Creatures. Always been a finicky spell with lots of hidden spawn table minutiae affecting power

Level 7:
* Unchanged: Haunt (great spell)
* Unchanged: Malign Gateway (great spell)
* Unchanged: Spellforged Servitor (unique spell)
* Removed: Summon Hydra (boring)
* Removed: Monstrous menagerie (boring)

Level 8:
* Unchanged: Summon Horrible Things. Basically boring, but with the removal of Monstrous Menagerie we need at least one high level multi-summon.
* Modified: Summon Greater Demon. Bumped up from L7. Always summons a tier1 demon (was tier1 or 2). It's always initially friendly, but might become hostile before despawning based on spellpower (was not always initially friendly, and tier 1 summons always became hostile).

Level 9:
* Unchanged: Dragon's Call (would like to make this a permacharm)

---
This change is [Reviewable](https://reviewable.io/reviews/hellmonk/hellcrawl/52)

### CODE REVIEW

**Comment by goodcoolguy** [comment]
I don't think the problem with summoning (power-wise) has to do with the number of spells or really the specific content. The big problem is the path blocking and to a lesser but still significant extent the line of fire blocking and monster distracting. 

The direction to go in nerfing the summonings school, in my opinion, is making the summoned monsters unable to block the approach of monsters. Two similar approaches would be to make monsters despawn summons if they walk through them or make monsters able to switch places with summons. The first could be flavored as "illusions." The first is the better approach imo. There's some tactics to getting your guys behind and around monsters rather than in front of them. It also radically reduces the power level of these spells, makes them useless in corridors and other normally advantageous terrain, etc.

Variations on this idea where monsters fire things through the illusory monsters to despawn them would work too.

This leaves the significant problem of the spamminess of summons, but this can be addressed through interface improvements, automatic casting/permasummons, and lower summon caps. It would be best to see allies get to a better place balance-wise before getting too far into interface issues imo.

**Comment by alexjurkiewicz** [comment]
Just a bump to say I still believe in this PR.

Something I want to emphasise is that I think it's a very hellcrawl PR given it's removing things 💁. But I do believe Crawl has too many spells that overlap, and cutting some is going to give the remainder more room to be unique.

**Comment by goodcoolguy** [comment]
Was just thinking about Mana Viper on a walk. While I still think what I outlined above is the right way to go on summons, for the time being Mana Viper could be improved a lot by reducing the summon cap to 1. I'd also like to see random placement for Lightning Spire. Targeting spells is bad in general, but manual placement of a magic immune, path/line of fire blocking summon is just goofy. 

It would be good to move on permasummons at some point in the near future. The mechanics of spectral weapon and battlesphere work reasonably well. A generalized version of those mechanics that encompasses other targeted actions (throwing, wands, hexes, shouts, etc.) as well as non-targeted effects that damage or otherwise affect monsters would probably work fine. The spectral weapon cooldown combined with "illusion" mechanics as above would round out the package pretty well imo. 

Also, summon butterflies doesn't work for me as a level 1 spell. Similarly for summon imp (recommend level 3 for that one).

**Comment by goodcoolguy** [comment]
While I'm drunk, let me expand on a few things. Regarding targeting, it would be really great if spells worked as a part of doing other things in general, with the targeted spell effect being the exception rather than the rule. This is the appeal of spectral weapon/battlesphere mechanics. "Targeting ground," which is to say targeting something, most often an empty space, that is not a monster is particularly bad -- some major offenders here are lightning spire, as mentioned, conjure flame, fireball, formerly glaciate, freezing cloud, and mephitic cloud. The wand of scattershot is also problematic, but because it can be used only a few times in a given game, I'm willing to give it a pass. (This is not to say I like LOS effects like ozocubo's refrigeration and shatter, but that's another discussion.)

The basic models for "triggered magic effects" already in hellcrawl are infusion and spectral weapon. (Of course, there's also trigger-on-kill, but let's not go there for now.) Spectral weapon is the basic model for summons/illusions as I've said. Infusion is a good model for a number of other effects, including portal projectile and hexes. Player hexes that operate on a permacharm model and trigger on attacks, whether ranged or melee, have a lot of potential. Relatively weak effects like distraction or even corona can work as a side effect of an attack. A low percentage slow effect could work on ranged attacks, as could a low percentage sleep/confuse/tukima's effect on melee. All would produce much cleaner gameplay than the usual procedure of spamming hexes then going Fist of the North Star on the affected monster. 

As for clouds, freezing cloud has already come in for a major nerf in dcss with the LOS requirement for persistent clouds (ofc this also affected cflame, poison cloud etc.). I would say this is a characteristic example of dcss refusing to go all the way. It is tedious, they posit, to cast a damage over time cloud spell on a monster and break LOS or bugs bunny door them to death, but the problem is actually with the LOS/door part, they ask us to believe, not the damage over time. I strongly suspect the damage over time is the culprit here, along with the ease of keeping the monster from directly interacting with the player, i.e. out of melee range. Conjure flame is not as problematic in this regard, since the limitations of the spell make the most common use cases that actually kill monsters involve body blocking.

I would not be sad to see freezing cloud removed (or replaced with something totally different, e.g. frostbite-like cloud on melee placement). Conjure flame could be improved by automatic targeting, namely always place the flame adjacent to the player and always on the tile closest to the nearest monster. If there is ambiguity, place it randomly among options that qualify by the above criterion. Experience with blink suggests that where this sort of randomization can be influenced through positioning, the result is interesting gameplay. Of course, the spell should never place a cloud on a monster, so we should really say the "nearest nonadjacent monster" above. This creates some potential for the player to get screwed by sloppy positioning, which is a good and needed nerf to a fairly broken spell.

For fireball, I would look to ignition mechanics. Fiddling with fireball targeting to avoid self-damage is purely annoying in reasonably competent play. Simply target the closest monster automatically with an ignition-style friendly fireball. Again, if there is ambiguity, randomize. A similar approach should also work with mephitic cloud, though it would surely take more work. Hell, might even work with fcloud.

**Pull request closed without merging**
