### PR TITLE
What? Your kobold is evolving!

### PR DESCRIPTION
**Pull request by yrmvgh**
everyone's favorite feature from dcssca.

(in this case, "everyone" is me)

### CODE REVIEW

**Comment by Sandman25DCSS** [comment]
You are not alone, I liked this feature too.

**Comment by alexjurkiewicz** [comment]
I liked this feature too, but is it in the hellcrawl spirit? I hope so. Also, was there additional handling in dcssca to ensure Ko never lost evolution?

**Comment by yrmvgh** [comment]
https://github.com/jeremygurr/dcssca/blob/2c94cca697e36bb42dc915297a58fef82e320221/crawl-ref/source/timed_effects.cc#L897
As far as I know, no. Having it as a racial feature seems to have been enough. Is there anywhere else other than the kobold racial stuff that I should doublecheck? Timed_effects seems to have all the handling, and it doesn't treat kobolds special.

I think it's in the hellcrawl spirit because hellcrawl deleted boring races, and of the surviving races, kobold and human are the most boring. This fixes that, though much more conservatively than dcssca did. To be fair, I'd try to put it in even if it **wasn't** in the hellcrawl spirit, so I'm not the best judge. :)

**Comment by Hellmonk** [comment]
Hmm, I'll think about it. I also thought about making kobolds a very low stat, high apt species but never committed to doing it. Maybe I'll do both...

**Comment by yrmvgh** [comment]
Evolution could also be slapped on any of the Removed races to give them pizazz. UC centaurs rippling with aux attacks. Mountain dwarves that delved too deep and are now irradiated. "Sludge" and "mutate" are words that go well together thematically.

**Pull request merged**
