### PR TITLE
Form bonuses

### PR DESCRIPTION
**Pull request by alexjurkiewicz**
Add some form spellpower scaling:

* Blade Hands base damage
* Spider Form EV
* Dragon Form base damage

---
This change is [Reviewable](https://reviewable.io/reviews/hellmonk/hellcrawl/44)

### CODE REVIEW

**Comment by alexjurkiewicz** [comment]
PS, these scaling numbers are all basically made up from gut feeling. I haven't tested through to lategame at all beyond basic wizmode sanity checking

**Comment by goodcoolguy** [comment]
just wanted to push back on the comment that "[n]ow that forms are permanent in Hellcrawl we want spellpower to matter for more than just reserved MP amount." If spellpower dependence is not necessary in dcss, it's not necessary here either. If the damage is too high when it's first available, then the thing to do is make it harder to get online. A good way to do that would be to move blade hands out of book of changes and replace it with statue form.

**Comment by alexjurkiewicz** [comment]
That's a fair point.

One issue I have with Tm playstyle in hellcrawl (and vanilla to a lesser extent) is that it encourages hard breakpoint type skilling. You train magic schools until your new form is castable and then you exist in it permanently. Compare to learning Fireball, where you keep on training fire magic to increase the spellpower. Of course the Tm-style skilling is like weapon mindelay -- you don't really bother training weapon damage above that point.

**Comment by goodcoolguy** [comment]
Spells that don't have a straightforward numerical component to them, like fireball and other direct damage spells, have this breakpoint issue, it's true. Yet my feeling is that the numerical scaling stuff is worse mechanically than the breakpoints. In the long run, it would be better to move to a system where whether you can cast something is binary and based on breakpoints that are easy to understand. 

Crawl magic has all these complex continuous systems that seem built for numerical scaling, yet the effects that give crawl magic is distinctiveness have a binary on/off nature, e.g. most duration effects, including transmutations, ally producing spells, and cloud producing spells. Maybe numerical scaling is actually bad.

**Comment by alexjurkiewicz** [comment]
I still believe in this PR, and will update it if you decide to #believe in it too.

**Pull request closed without merging**
