### PR TITLE
give players a compelling reason to pick Og

### PR DESCRIPTION
**Pull request by yrmvgh**
other than the (currently) super high mace apt
(not a "meme", but based on some chit-chat in ##crawl)

### CODE REVIEW

**Comment by goodcoolguy** [comment]
In my opinion, there is no really compelling reason for ogre to exist either as it does now in hellcrawl or as it does in dcss. It is a lot like a troll, except that it is less fun to play. 

Again, in my opinion, it would be best to merge species rather than maintain the superficially varied but actually quite same-y situation of dcss. In particular, I would like to see a merger of ogre, demigod, and demonspawn into a single large species with big stats, flat apts, the atheist conduct, and demonspawn mutations. Call it a "titan" or something, some kind of primordial godlike giant of myth for "flavor."

**Comment by yrmvgh** [comment]
All this time, I thought goodcoolguy was @Hellmonk because some of the earliest commits are from @goodcoolguy . Well hello whoever you are! I really like the idea of merging Dg and Ds actually. I'm curious what hellmonk's thoughts are on that. I'd be happy to support your PR for that, or mayyyybe I can take point on that if necessary. Thanks for sharing your thoughts!

I still like ogre as "the spellcasting fat one" and troll as the "melee fat one". But if hellmonk wants to merge as aggressively as you're talking about, I can get behind it.

I still like felids and wish they weren't removed, but I can see how spriggan is a kinda-similar but better design. So along those same lines I'd be willing to get behind this super merging, but would rather try to differentiate the species before scrapping them.

**Comment by Hellmonk** [comment]
I think ogre might be a good candidate for the LOS 8 mutation (flavor: you are really big). Since LOS 8 is a nerf, we could either buff their hp to +4, give them regularcrawl magic apts, or both. Troll hp could definitely use a nerf if ogre is going to be modified along these lines. Otherwise, I don't object to some sort of merger or outright removal of og, but it's at the back of my list of priorities right now.

**Comment by goodcoolguy** [comment]
tbh total reimagining of crawl species or removal of the idea of species altogether are more promising ideas than incremental changes to existing crawl species. prob is that players coming from crawl face a steeper learning curve dealing w/ hellcrawl species that aren't the same as dcss species. otoh, it's not like the species system is worth a damn in the first place -- most species differ primarily in aptitudes, which is a fucking joke. 

if hellcrawl is going to have significantly different species, they gotta be really different, different names, fundamentally different designs, etc. so that you at least have the novelty factor going. 

far better than the combo system is a hero model where all aspects of a character (apts, mutations, size, starting god, starting skills, starting equipment, lol movespeed smh, etc.) are part of a single package, e.g. instead of something like SpEn, you get The Enchantress, instead of FoAK you get The Corrupter, but you don't have shit like MfFE or TrSu. When you've dispensed w/ the combo system, you open up a whole new world of crawl design because you don't have to worry about all the weird shit players can do with a given species or background design that can be paired with whatever other thing. Constraining the player to what makes sense and works from a design perspective is incredibly good and cool.

**Comment by Hellmonk** [comment]
Closing bc I merged demigod and ogre into titan.

**Pull request closed without merging**
