### PR TITLE
Zin now hates everything, Hep is moved to the good_gods

### PR DESCRIPTION
**Pull request by yrmvgh**
Zin is a god of intolerance and wrath, a fun little twist for hellcrawl may be to split him off by himself.

Of the other gods in crawl who could join the trinity:
* veh would be fun and interesting ("Let the sinners burn in hellfire!") but doesn't use invo so it makes for a somewhat worse swap from ely/tso
* hep uses invo, but has some pretty macabre themeing and an unsettling ultimate ability
* the new Council God could be a great fit, but again doesn't use invo. also it isn't done being tested. also hellmonk hates it.
* beogh is gone
* ash is gone
* most of the remaining gods are evil, chaotic, or "naughty" themed
* gozag and zin could be buddies, but not gozag and ely

Hep seems like a good fit to me. Revering departed ancestors means not necromancifying corpses, which is currently allowed but wouldn't be, if Hep became a good god. Respect, tradition, ancestor worship, I get a big Shinto vibe from this god, and Shinto is very good at co-existing with other traditions and systems of belief - maybe even co existing with that jerk TSO!

### CODE REVIEW

**Comment by goodcoolguy** [comment]
Some random thoughts on hellcrawl religion:

- I like hep... as yred reform. I posted about this on tavern some time ago. The single good ally model is good, yred-style ally spam is garbage. Already axed one god w/ ally spam playstyle. The solution is make the enslave soul spectral ally from yred respawn like hep ancestors (i.e. respawns when killed), adjust yred abilities to work w/ the ally (like drain life also heals spectral ally, pain mirror affects spectral ally), get rid of the permanent ally gifts, remove hep.

- Zin abilities are cool, but the development curve of the god sucks. Ely abilities are lame af, but the development curve is good so that Ely is a powerful god and Zin sucks ass for too much of the game to be worth taking. What I would like to see is passive recite along the lines of Ru's passives (also remove Ru smdh), move the vitalize ability to * or sth to speed up the curve, maybe earlier, more expensive imprison. Maybe just shift all abilities down by one *. 

- TSO is garbage, makhleb for extended basically. Could be folded into Zin by giving Zin a silver brand ability and bringing back the silver slays undead thing. Or just holy wrath brand ability lol. Folding the divine shield ability into vitalize could be good too. Need vitalize to actually do something without a lot of investment. rN+ would be good too, since that actually does something in hellcrawl. Pretty much consolidate "good gods" into Zin is what I'm thinking.

- Following on the previous bullet point, when you look at active god abilities, you gotta ask how it compares to known good ones, e.g. heroism. If the effect is significantly more subtle than heroism with 3-6 invo, e.g. gives you rpois and +1 str/dex/int, it might not work as a god ability.

- Been meaning to try new new new nemelex. Current dcss nemelex is completely broken imo. Legendary decks of summoning just dump panlords on you, all decks are extremely powerful within like 100 turns of joining. The latter problem may be exacerbated by making every deck ornate tbh. The inventory management improvement is prob quite rad tho.

- Tiered altar generation -- it'd be rad to remove temple and make all altars overflow. I would then suggest tiered altar generation where some gods tend to generate earlier than others to create greater inducement to join. Thinking like Tier 1 (~d:1-4): dith, makh, sif, qaz, chei; Tier 2 (~d:4-7): kiku, veh, yred, new zin, nem; Tier 3 (d:7-10) oka, trog, gozag. Would want to add some randomization to make earlier/later spawns possible but more or less follow some schema like the above. 
- Ecumenical altar reform -- totally random ecumenical altars are bad, fam. Would be rad to define some subgroupings of gods that fit some character development path and package them into random altars that give you an idea of what you might get when you join. Pretty much something that guarantees you're not going to get sif on a gladiator or trog on a fire elementalist...
- Oka is rad af in hellcrawl. Gold standard for god power levels going forward, imo.

**Comment by goodcoolguy** [comment]
Sorry to make this space into a forum again, but...

Invocations reform -- a rad idea whose time has come.

Invocations is essentially a very spoiler-y xp sink. Knowing how much invocations it's worth getting is arcane and varies by god, but can make a significant difference in how a character develops if it's done wrong (common w/ new/bad players). 

Looking at gods that use invocations, it is unclear why it is there, what purpose it serves in terms of balance, etc. The role of invocations can easily be fulfilled by character xl and piety (as already happens w/ some existing gods). 

Finally, the existence of the skill wedges an extra unneeded dimension of complexity into the game w/o even giving it a name that conveys what the hell it does. Like, in ordinary English both the words "invocations" and "evocations" are exotic and mean roughly the same things. Related, rename evocations something like "magic device" or sth. 

Anyway, might be worth considering in the course of linearization of hellcrawl formulas.

**Comment by yrmvgh** [comment]
Nothing can happen until hellmonk either dies trying, or finishes Full Dungeon Linearity, the Rewrite Of All Time!

Until then, I started my own fork to keep myself busy. https://crawl.develz.org/tavern/viewtopic.php?f=17&t=23209

**Comment by Hellmonk** [comment]
Not gonna do this in the immediate future. I'm not sure that I want to keep the holy trinity flavor at all, it's kind of bad/overdone imo.

**Pull request closed without merging**
