### PR TITLE
Make elec brand worse

### PR DESCRIPTION
**Pull request by alexjurkiewicz**
Reduce damage from 5 + random2(13) (average 11.5) to 4 + random2(8)
(average 8) -- a 30% reduction.

---
This change is [Reviewable](https://reviewable.io/reviews/hellmonk/hellcrawl/40)

### CODE REVIEW

**Comment by Hellmonk** [comment]
I don't object to nerfing elec brand further, but for the record it's already doing 3 less damage on average than regular DCSS elec brand. Would want to see some fsims before I nerf it again.

**Comment by alexjurkiewicz** [comment]
Existing Hellcrawl stats (Dungeon Crawl Stone Soup v3.33-hellcrawl-59-ge1be2d5):

With HuFi XL1 (3 fighting, 2 blades/maces & staves, no shield equipped) vs Ogre:
```
            AvHitDam | MaxDam | Accuracy | AvDam | AvTime | AvSpeed | AvEffDam
 Attacking:      1.7 |      5 |      78% |   1.3 |    90  |  1.11 |      1.5 (dagger)
 Attacking:      5.5 |     22 |      77% |   4.3 |    90  |  1.11 |      4.7 (elec dagger)
 Attacking:      4.3 |     16 |      77% |   3.4 |    90  |  1.11 |      3.8 (proposed elec dagger)
 Attacking:      2.5 |      8 |      78% |   2.0 |    90  |  1.11 |      2.2 (flaming dagger)
 Attacking:      7.5 |     20 |      70% |   5.3 |   150  |  0.67 |      3.6 (double sword)
 Attacking:     11.2 |     35 |      69% |   7.8 |   150  |  0.67 |      5.2 (elec double sword)
 Attacking:     10.0 |     29 |      71% |   7.1 |   150  |  0.67 |      4.8 (proposed elec double sword)
 Attacking:     10.0 |     27 |      71% |   7.2 |   150  |  0.67 |      4.8 (flaming double sword)
 Attacking:      9.1 |     24 |      66% |   6.0 |   170  |  0.59 |      3.5 (great mace)
 Attacking:     13.1 |     41 |      69% |   9.1 |   160  |  0.62 |      5.7 (elec great mace)
 Attacking:     11.9 |     33 |      68% |   8.2 |   160  |  0.62 |      5.1 (proposed elec great mace)
 Attacking:     12.0 |     34 |      66% |   7.9 |   170  |  0.59 |      4.7 (flaming great mace)
```

With HuFi XL14 (10 fighting, 14 blades/maces & staves, no shield) vs Death Yak:
```
            AvHitDam | MaxDam | Accuracy | AvDam | AvTime | AvSpeed | AvEffDam
 Attacking:      0.7 |      9 |      84% |   0.6 |    50  |  2.00 |      1.1 (dagger)
 Attacking:      4.4 |     24 |      85% |   3.7 |    50  |  2.00 |      7.5 (elec dagger)
 Attacking:      3.2 |     18 |      84% |   2.7 |    50  |  2.00 |      5.4 (proposed elec dagger)
 Attacking:      0.9 |     12 |      85% |   0.8 |    50  |  2.00 |      1.6 (flaming dagger)
 Attacking:      6.9 |     30 |      81% |   5.6 |    90  |  1.11 |      6.3 (double sword)
 Attacking:     10.8 |     47 |      81% |   8.8 |    90  |  1.11 |      9.8 (elec double sword)
 Attacking:      9.8 |     38 |      81% |   8.0 |    90  |  1.11 |      8.9 (proposed elec double sword)
 Attacking:      9.2 |     40 |      81% |   7.5 |    90  |  1.11 |      8.4 (flaming double sword)
 Attacking:      9.5 |     38 |      79% |   7.5 |   100  |  1.00 |      7.5 (great mace)
 Attacking:     13.4 |     50 |      79% |  10.7 |   100  |  1.00 |     10.7 (elec great mace)
 Attacking:     12.0 |     45 |      80% |   9.7 |   100  |  1.00 |      9.7 (proposed elec great mace)
 Attacking:     12.1 |     55 |      79% |   9.7 |   100  |  1.00 |      9.7 (flaming great mace)
```

With HuFi XL24 (20 fighting, 20 blades/maces & staves, no shield) vs Orb Guardian:
```
            AvHitDam | MaxDam | Accuracy | AvDam | AvTime | AvSpeed | AvEffDam
 Attacking:      0.7 |     11 |      70% |   0.5 |    50  |  2.00 |      1.0 (dagger)
 Attacking:      4.5 |     26 |      68% |   3.1 |    50  |  2.00 |      6.2 (elec dagger)
 Attacking:      3.2 |     22 |      69% |   2.2 |    50  |  2.00 |      4.4 (proposed elec dagger)
 Attacking:      1.1 |     16 |      69% |   0.8 |    50  |  2.00 |      1.5 (flaming dagger)
 Attacking:      8.4 |     44 |      64% |   5.4 |    70  |  1.43 |      7.7 (double sword)
 Attacking:     11.8 |     54 |      63% |   7.5 |    70  |  1.43 |     10.7 (elec double sword)
 Attacking:     10.9 |     51 |      63% |   6.9 |    70  |  1.43 |      9.9 (proposed elec double sword)
 Attacking:     10.9 |     66 |      64% |   7.0 |    70  |  1.43 |     10.0 (flaming double sword)
 Attacking:     11.3 |     54 |      60% |   6.8 |    70  |  1.43 |      9.7 (great mace)
 Attacking:     14.9 |     68 |      62% |   9.3 |    70  |  1.43 |     13.3 (elec great mace)
 Attacking:     14.2 |     60 |      62% |   8.9 |    70  |  1.43 |     12.7 (proposed elec great mace)
 Attacking:     15.0 |     74 |      62% |   9.3 |    70  |  1.43 |     13.3 (flaming great mace)
```

In short, current elec is strictly superior to flaming/freezing in terms of damage except for great mace/GC/GSC, where it is equivalent.

**Comment by alexjurkiewicz** [comment]
Based on the stats above, this PR would make elec damage approximately equal to freezing/flaming from around mindelay onwards for 0.6 and 0.7 speed weapons. On 0.7 weapons it would end up slightly (5%) worse.

If anything, I think my nerf should be greater. Elec is still much better on fast/low damage weapons than multiplicative brands compared to how much better multiplicative brands are on slow/high damage weapons.

**Comment by alexjurkiewicz** [comment]
I still believe in this PR.

**Pull request closed without merging**
