### PR TITLE
Remove spellcasting.

### PR DESCRIPTION
**Pull request by alexjurkiewicz**
Spell levels and max MP get the same base calculation:
  xl + int * (xl/27)

(Max MP gets flat +1 added, as well as all other previous modifiers such
as species and mutations.)

Spellpower from spellcasting skill is discarded.

Spellcasting is removed from all backgrounds.
* Wizard background gets one point in all their beginning book schools.
* All other backgrounds which previously had spellcasting get +1
  to every spell school they already started with.

Various other changes to hidden logic, especially around acquirement and
item creation. (Randbook levels, book vs manual acquirement, acquirement
armour ER, etc.)

### CODE REVIEW

**Comment by alexjurkiewicz** [comment]
The new spell level / max mp calculation is picked to give very similar numbers as before at low XL and vaguely similar at high XL for chars that prioritise int. Chars that don't prioritise int and how the growth compares in midgame might be very different.

**Comment by alexjurkiewicz** [comment]
Also I didn't really compare starting spell fail%/power before/after this change yet. I'm guessing you'd like these sort of numbers Hellmonk?

**Comment by goodcoolguy** [comment]
http://i.imgur.com/QONVIyz.gif

[fire emoji][fire emoji][fire emoji][fire emoji][fire emoji]

**Comment by Hellmonk** [comment]
This is obv worth doing long term, I mentioned that there might be some problems re: int dependence in irc. I think the ideal solution is to have max mp based only on xl and species; this is probably reachable within a couple months or so. Until then I'll sit on it and see if anything really choice comes out.

**Comment by alexjurkiewicz** [comment]
yep, makes sense. I think the approach needs some top down decisions, eg
deciding how characters "should" look in various scenarios (eg Mi vs Hu vs
DE / Fi vs Sk vs FE / XL1 vs XL10 vs XL20) and then engineering MP/spell
level from that. One thing is for sure in that this will be a relatively
large divergence from vanilla crawl balance. Some scenarios will get buffed
and some will get nerfed. It's a matter of deciding how best to distribute
changes.

**Comment by goodcoolguy** [comment]
Int dependence is good, imo. You want low int casters doing charm/utility stuff to be more constrained by max mp. 

Main problem I could see here is the evocations/invocations contribution to max mp. This could be removed along with mp costs from nonmagic effects. Evocable equipment is kind of bad anyway, god abilities can easily depend only on piety, especially since the numerical piety is available in the interface now -- very easy to see what stuff costs.

**Comment by alexjurkiewicz** [comment]
> Main problem I could see here is the evocations/invocations contribution to max mp. This could be removed along with mp costs from nonmagic effects. Evocable equipment is kind of bad anyway, god abilities can easily depend only on piety, especially since the numerical piety is available in the interface now -- very easy to see what stuff costs.

This patch removes the contribution of evo/invo to MP under all conditions. I think equipment is all pretty low-mp use, but god abilities might need MP reduction, especially on the higher end. Personally abilities that use too many resources annoy me, so I'd rather (almost all) divine abilities required 0 mp.

**Comment by Hellmonk** [comment]
Going to merge some variant of this before the next "big update" on the main servers. Posting here so I can't flake on it.

E: cbro never updated with the new stuff last time so I'm pushing a mini update first, this is still going in the next one tho

**Comment by alexjurkiewicz** [comment]
Sick

**Comment by Hellmonk** [comment]
Merging now. A little worried there will be some weird behavior with the spell levels part of this change, but that should be easy enough to fix.

**Pull request merged**
