### PR TITLE
Gnolls and kobolds with a good, cool skill system. 

### PR DESCRIPTION
**Pull request by goodcoolguy**
This is a response to discussion in dcss about cynos/bultungins/gnolls and the hellcrawl take on them, kobolds. The high skill/low stat thing never worked for me and the weird skill systems that have been tried in trunk... just blows my mind that stuff ever got that far. This take on the issue tries to get that broad/generalist skill set without forcing the player to manually train every damn skill in the game. 

Idea is simple: Each start with skills determined by background and species aptitudes, but get no further normal skill growth. The rest is given by an XL-based bonus scaling from 0 to 13 or 0 to 12, with .5 skill levels added per XL starting at level 2 or 4.

The gnoll has higher physical skill apts, the kobold higher magic apts. The kobold also gets a bigger bonus to magic skills. Gnoll has human-like stats, kobold gets 6/11/8 stats.

I've done pretty limited testing. I played a full game with a KoFE, which was consistently strong throughout, and got several gnolls killed. The numbers could probably use some adjustment for balance, but the concept seems good. Not screwing around with the skill menu is great.

edit: There are some things to clean up tho. Manuals should be marked useless, sif boost should be updated to give a straight skill level boost like heroism instead of the weird skill point stuff dcss-ash (RIP) does or it won't work right/well with gnoll/kobold skills. It would be good to make the skill menu noninteractive and tell the player what's going on with gnoll/kobold skills too. Wanted to gauge interest in the concept first.

The gnoll is quite ordinary outside of the skill system. While I basically just copypasta'd half the original Bultungin commit to fashion the gnoll, didn't bother with any of the mutations since lol whatever. Pretty much left the kobold the same mutation-wise, still has evolve. 

The apts are mostly +6 and +3 with +4s for evo and invo. You start strong but you start to feel the relative weakness of your primary skills around mid-dungeon. 

One last thing, a bit of a hack, I made the number of spell levels available independent of spellcasting skill. It's 3\*XL for gnoll and 4\*XL for kobold, so it's like a hell of a lot of slots to encourage use of a broad array of spells. Maybe too much, can always trim it back.

### CODE REVIEW

**Comment by alexjurkiewicz** [comment]
Suggestion: just put in one of these species so we can test the concept without hellcrawl needing to commit to it.

**Comment by goodcoolguy** [comment]
I think the hellcrawl audience would accept a removal down the road without a lot of backbiting. I need to test gnolls a bit more to figure out if the niche I'm going for there really works though. I like the kobold. Kobold has the advantage that it's already a species, but the disadvantage that a lot of that mid-10s breakpoint equipment either goes from 1-handed to 2-handed or is no longer mid-10s with shields. Anyway, I'll consider the suggestion.

**Comment by goodcoolguy** [comment]
Alright, I turned off gnoll character generation, but code and species enumeration entry remains.

**Comment by goodcoolguy** [comment]
Nerfed kobold down to a bonus of 12 to all skills at xl 27, knocked magic aptitudes down to +3 (this actually doesn't make that much difference). I recommend giving it a try. I feel alright about the balance and the gameplay is quite clean imo. Makes good book guys, like a deep elf but not as fiddly and with a stronger push to stick to mid level stuff.

**Comment by alexjurkiewicz** [comment]
I figured it was better to talk about Ko balance on the commit, rather than in this PR https://github.com/Hellmonk/hellcrawl/commit/133334ba9a1aaf585d612dfe099799fb923597f7

**Pull request merged**
